services:
  traefik:
    command:
      - --global.sendanonymoususage=false
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.http.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - --entrypoints.websecure.http.tls.domains[0].main=${PUBLIC_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${PUBLIC_DOMAIN}
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.storage=/etc/traefik/acme/acme.json
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.dnschallenge=true
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.dnschallenge.delaybeforecheck=0
      - --ping=true
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
